DECLARE @TEXTO NVARCHAR(MAX);
DECLARE PONTEIRO CURSOR 
FOR 
	SELECT CONCAT('DBCC CHECKDB (', QUOTENAME(NAME),') ')
	FROM SYS.DATABASES 
	WHERE 
		STATE_DESC = 'ONLINE' 
		AND DATABASE_ID > 4 AND STATE = 0
	ORDER BY NAME 	
OPEN PONTEIRO 
FETCH PONTEIRO INTO @TEXTO
WHILE (@@FETCH_STATUS = 0)
BEGIN
	EXECUTE SP_EXECUTESQL  @TEXTO; 
	FETCH NEXT FROM PONTEIRO INTO @TEXTO;		
END
CLOSE PONTEIRO;
DEALLOCATE PONTEIRO;	
GO
