DECLARE @TEMPORARIO TABLE (NOME VARCHAR(100), TEXTO VARCHAR(MAX))

INSERT INTO @TEMPORARIO
SELECT NAME, CAST(OBJECT_DEFINITION(P.OBJECT_ID) AS VARCHAR(MAX))
FROM SYS.PROCEDURES AS P

SELECT * FROM @TEMPORARIO WHERE TEXTO LIKE '%DS_TRAVA_DATABASE_LIBERACAO%'