IF OBJECT_ID ('ACERTA_IDENTITY', 'P') IS NOT NULL
	DROP PROCEDURE ACERTA_IDENTITY;
GO
CREATE PROCEDURE ACERTA_IDENTITY AS
	DECLARE @TEXTO NVARCHAR(200);
BEGIN
	DECLARE PONTEIRO CURSOR 
	FOR 	
		SELECT 
			CONCAT('DBCC CHECKIDENT(', Name, ',RESEED, 2)') AS STRING
		FROM 
			sysobjects so
		WHERE 
			so.xtype = 'U' 
			and
			(SELECT OBJECTPROPERTY(OBJECT_ID(Name),'TableHasIdentity')) > 0
			and
			( select coalesce(IDENT_CURRENT( Name ),0)) < 2

		union all

		SELECT 
			CONCAT('DBCC CHECKIDENT(', Name, ',NORESEED)') AS STRING
		FROM 
			sysobjects so
		WHERE 
			so.xtype = 'U' 
			and
			(SELECT OBJECTPROPERTY(OBJECT_ID(Name),'TableHasIdentity')) > 0
			and
			( select coalesce(IDENT_CURRENT( Name ),0)) >= 2


	OPEN PONTEIRO 
	FETCH PONTEIRO INTO @TEXTO
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		EXECUTE sp_executesql  @TEXTO;
		FETCH NEXT FROM PONTEIRO INTO @TEXTO;
	END
	CLOSE PONTEIRO;
	DEALLOCATE PONTEIRO;
END
GO

EXEC ACERTA_IDENTITY