
USE [master]
GO

DISABLE TRIGGER [Prevent_DB_Drop] ON ALL SERVER 
--ALTER database [ANNASEGABBY_2890] set offline with ROLLBACK IMMEDIATE;
DROP DATABASE [TESTE_EDMAIS_DANILO_TESTE41];
ENABLE TRIGGER [Prevent_DB_Drop] ON ALL SERVER 
GO