SELECT 
	TABELAS.NAME AS TABELA, 
	COLUNAS.NAME AS COLUNA, 
	TIPOS.NAME AS TIPO, 
	COLUNAS.LENGTH AS TAMANHO, 
	COLUNAS.ISNULLABLE AS EH_NULO 
FROM 
	SYSOBJECTS TABELAS INNER JOIN 
	SYSCOLUMNS COLUNAS ON (TABELAS.ID = COLUNAS.ID) INNER JOIN 
	SYSTYPES TIPOS ON (COLUNAS.USERTYPE = TIPOS.USERTYPE) 
WHERE 
	TABELAS.XTYPE = 'U'
ORDER BY 
	TIPOS.NAME