WITH 
CHAVES AS (
	SELECT 
		OBJECT_NAME(CONSTRAINT_OBJECT_ID) FK,
		OBJECT_NAME(PARENT_OBJECT_ID) PAI,
		(SELECT NAME FROM SYS.COLUMNS C WHERE C.COLUMN_ID = FC.PARENT_COLUMN_ID AND C.OBJECT_ID = FC.PARENT_OBJECT_ID) COLUNA,
		OBJECT_NAME(REFERENCED_OBJECT_ID) FILHO
	FROM SYS.FOREIGN_KEY_COLUMNS FC  ),
COLUNAS_PK AS (
	SELECT 
		COL.COLUMN_NAME, 
		TAB.TABLE_NAME, 
		(SELECT USER_TYPE_ID FROM SYS.COLUMNS C 
		WHERE OBJECT_NAME(OBJECT_ID) = TAB.TABLE_NAME AND NAME = COL.COLUMN_NAME) USER_TYPE_ID
	FROM 
		INFORMATION_SCHEMA.TABLE_CONSTRAINTS TAB, 
		INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE COL 
	WHERE 
		COL.CONSTRAINT_NAME = TAB.CONSTRAINT_NAME
		AND COL.TABLE_NAME = TAB.TABLE_NAME
		AND CONSTRAINT_TYPE = 'PRIMARY KEY'),
COLUNAS AS (
	SELECT 
		OBJECT_ID ID_PAI, 
		OBJECT_NAME(OBJECT_ID) PAI,
		NAME AS COLUNA,
		COUNT(*) QT_COLUNAS_PK,
		STRING_AGG(COLUMN_NAME,',') _COLUNAS,
		C.COLUMN_ID,
		C.USER_TYPE_ID
	FROM SYS.COLUMNS C  JOIN COLUNAS_PK ON TABLE_NAME = C.NAME
	--WHERE C.NAME = 'NIVEL'
	GROUP BY OBJECT_ID, COLUMN_ID, NAME, C.USER_TYPE_ID)

SELECT 
		CONCAT('IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE NAME = ''FK_',PAI,'_',COLUNA,''')',
		'ALTER TABLE ', PAI, ' ADD CONSTRAINT FK_',PAI,'_',COLUNA,' FOREIGN KEY (',CASE QT_COLUNAS_PK WHEN 1 THEN COLUNA ELSE CONCAT(COLUNA, 'LOJA,', COLUNA) END,') REFERENCES ',
		COLUNA, '(',_COLUNAS,') GO')
FROM COLUNAS L
WHERE 
	L.COLUNA IN (SELECT NAME FROM SYS.OBJECTS) 
	AND NOT EXISTS (SELECT * FROM CHAVES H WHERE H.PAI = L.PAI AND H.COLUNA = L.COLUNA)
	AND EXISTS (SELECT TOP 1 COLUMN_NAME FROM COLUNAS_PK WHERE  TABLE_NAME = OBJECT_NAME(ID_PAI))
	AND L.USER_TYPE_ID = (SELECT TOP 1 USER_TYPE_ID FROM COLUNAS_PK WHERE  TABLE_NAME = OBJECT_NAME(ID_PAI))
	AND L.COLUNA NOT IN ('CEP', 'HASH', 'PRECOREGIAO', 'REJEICAO', 'CONCILIACAO', 'UNIDADE', 'ECF', 'PAIS', 'CFOP', 'LOJA')
	AND L.PAI NOT IN ('ENVIO', 'TEMPLATE_HTML')
ORDER BY PAI, COLUNA