
CREATE OR ALTER   VIEW [dbo].[VERSOESNOSCLIENTE] AS 

WITH 

LOGVERSOESLIBERADAS AS (
SELECT 
	CAST(DATA AS DATETIME) + CAST( HORA AS DATETIME) DATA, 
	ACAO, MENSAGEMLOG, CAST(RIGHT(MENSAGEMLOG, 4) AS INT) VERSAO
FROM LOGGERAL 
WHERE (ACAO = 'EDITAR VERSÃO USE' OR ACAO LIKE 'EDITOU VERS%') AND MENSAGEMLOG NOT LIKE '%NÃO FOI ENVIADO%' ),

VERSOES AS (
SELECT VERSAOID, V.VERSAO, DESCRICAO, MIN(DATA) DATA_LIBEROU_VERSAO, MAX(DATA) ULTIMA_ALTERACAO_VERSAO, RANK() OVER (ORDER BY MAX(DATA) DESC) AS RANKING
FROM LOGVERSOESLIBERADAS V JOIN VERSAO S ON S.VERSAOID = V.VERSAO
WHERE S.PRODUCAO = 1
GROUP BY VERSAOID, V.VERSAO, DESCRICAO),

DETALHESATUALIZACOES AS (
SELECT DISTINCT 
	E.ID AS ESTRUTURAID,
	UPPER(REPLACE(E.DESCRICAO, '_', ' ')) AS ESTRUTURA, 
	V.VERSAOID, 
	V.DESCRICAO AS VERSAO, 
	DATA_LIBEROU_VERSAO,
	ULTIMA_ALTERACAO_VERSAO,
	A.DATAEXECUCAO AS ULTIMA_ATUALIZACAO_CLIENTE,
	DATEDIFF(DAY, CAST(DATA_LIBEROU_VERSAO AS DATE), CAST(DATAEXECUCAO AS DATE)) AS DIAS_ATUALIZACAO_APOS_LIBERACAO,
	DATEDIFF(DAY, CAST(ULTIMA_ALTERACAO_VERSAO AS DATE), CAST(DATAEXECUCAO AS DATE)) AS DIAS_ATUALIZACAO_APOS_ULTIMA_ALTERACAO,
	(SELECT COUNT(*) FROM CLIENTE WHERE ESTRUTURAID = E.ID) LOJAS,
	RANKING
FROM ATUALIZACAO A JOIN 
	ESTRUTURACLIENTE E ON E.ID = A.ESTRUTURAID JOIN 
	VERSOES V ON V.VERSAOID = A.VERSAOID 
WHERE E.AMBIENTETESTE != 1 ),

VERSOESNOSCLIENTE AS (
SELECT * FROM DETALHESATUALIZACOES D1
WHERE ULTIMA_ATUALIZACAO_CLIENTE = (SELECT MAX(ULTIMA_ATUALIZACAO_CLIENTE) FROM DETALHESATUALIZACOES D2 WHERE D2.ESTRUTURAID = D1.ESTRUTURAID))

SELECT * FROM VERSOESNOSCLIENTE

GO