USE MASTER 
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'TABELA_INVENTARIO')
	DROP TABLE TABELA_INVENTARIO;
CREATE TABLE TABELA_INVENTARIO(BANCO VARCHAR(MAX), LOJA INT)
GO

DECLARE @TEXTO NVARCHAR(MAX);
DECLARE PONTEIRO CURSOR 
FOR 
	SELECT CONCAT('IF EXISTS (SELECT * FROM [', NAME, '].DBO.SYSOBJECTS WHERE XTYPE=''U'' AND NAME = ''SALDO_INVENTARIO'')BEGIN TRY USE [', NAME,'] 
			INSERT INTO MASTER.DBO.TABELA_INVENTARIO 		
			SELECT DB_NAME() BANCO,	L.CODIGO
			FROM LOJA L 
		END TRY BEGIN CATCH END CATCH; ') 
	FROM SYS.DATABASES WHERE STATE_DESC = 'ONLINE'
	ORDER BY NAME
OPEN PONTEIRO 
FETCH PONTEIRO INTO @TEXTO
WHILE (@@FETCH_STATUS = 0)
BEGIN
	EXECUTE SP_EXECUTESQL  @TEXTO; 
	FETCH NEXT FROM PONTEIRO INTO @TEXTO;		
END
CLOSE PONTEIRO;
DEALLOCATE PONTEIRO;
GO	

PRINT('SCRIPTS PREPARADOS. VAMOS COMEÇAR.')
		
DECLARE @TEXTO NVARCHAR(MAX);
DECLARE PONTEIRO CURSOR 
FOR 
SELECT CONCAT('PRINT ''BANCO ',BANCO, ' - LOJA ',LOJA,'''; EXEC [', BANCO, '].DBO.GRAVAINVENTARIO 2020, ', LOJA, ', ''20210101''') + CHAR(13)
FROM TABELA_INVENTARIO
OPEN PONTEIRO 
FETCH PONTEIRO INTO @TEXTO
WHILE (@@FETCH_STATUS = 0)
BEGIN
	EXECUTE SP_EXECUTESQL  @TEXTO; 
	FETCH NEXT FROM PONTEIRO INTO @TEXTO;		
END
CLOSE PONTEIRO;
DEALLOCATE PONTEIRO;
GO	