/*FORMATO CSV:
12;2020-01-13;54971.80;877.94;54093.86
*/

DROP TABLE IF EXISTS #TESTE
CREATE TABLE #TESTE (LOJA INT, DATA DATE, BRUTO NUMERIC (15,2), DESCONTO NUMERIC (15,2), LIQUIDO NUMERIC (15,2))

BULK INSERT #TESTE
FROM 'C:\USERS\SQLSERVICE\DOCUMENTS\CREDITOSLOJAS_20200113.CSV' WITH( FIELDTERMINATOR = ';', ROWTERMINATOR = '\N')

SELECT CONCAT ('EXEC INCLUI_CONTARECVENDACARTAO_CTC ''', DATA, ''', ', LIQUIDO, ',', DESCONTO, ',', LIQUIDO, ',', LOJA, ';') 
FROM #TESTE