USE master;
GO
ALTER DATABASE CONSTANCE_3262
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE CONSTANCE_3262
SET READ_COMMITTED_SNAPSHOT ON;
GO
ALTER DATABASE CONSTANCE_3262
SET MULTI_USER;
GO
