
CREATE OR ALTER TRIGGER TESTE_TRIGGER_REPLICADOR_COR_I
   ON  COR
   AFTER INSERT
AS 
BEGIN
	SET IDENTITY_INSERT BANCO_TESTE_PRINCIPAL.DBO.COR ON
	INSERT BANCO_TESTE_PRINCIPAL.DBO.COR (LOJA, CODIGO, DESCRICAO, DATULTALT) 	
	OUTPUT INSERTED.*
	SELECT LOJA, CODIGO, DESCRICAO, DATULTALT FROM INSERTED;
	SET IDENTITY_INSERT BANCO_TESTE_PRINCIPAL.DBO.COR OFF
END
GO

CREATE OR ALTER TRIGGER TESTE_TRIGGER_REPLICADOR_COR_U
   ON  COR
   AFTER UPDATE
AS 
BEGIN
	DECLARE @LOJA INT
	DECLARE @CODIGO INT
	DECLARE @DESCRICAO VARCHAR(MAX)
	DECLARE @DATULTALT DATE

	SELECT @LOJA = LOJA, @CODIGO = CODIGO, @DESCRICAO = DESCRICAO, @DATULTALT =DATULTALT
	FROM INSERTED

	UPDATE BANCO_TESTE_PRINCIPAL.DBO.COR 
	SET DATULTALT = @DATULTALT, DESCRICAO = @DESCRICAO 	
	OUTPUT INSERTED.*
	WHERE CODIGO = @CODIGO AND LOJA = @LOJA
END
GO

CREATE OR ALTER TRIGGER TESTE_TRIGGER_REPLICADOR_COR_D
   ON  COR
   AFTER DELETE
AS 
BEGIN
	DECLARE @LOJA INT
	DECLARE @CODIGO INT

	SELECT @LOJA = LOJA, @CODIGO = CODIGO
	FROM DELETED

	DELETE FROM COR 	
	WHERE CODIGO = @CODIGO AND LOJA = @LOJA

	SELECT * FROM DELETED
END
GO