USE MASTER;
DECLARE @SELECT NVARCHAR(MAX) = '';

SELECT @SELECT += CONCAT('select COUNT(*) AS CONTADOR from terminal l where l.forcardownloadversao <> 1 and L.UTILIZASATNFCE = 2  ' 
		) 
	FROM SYS.DATABASES WHERE STATE_DESC = 'ONLINE' AND NAME NOT LIKE '%TESTE%'
	ORDER BY NAME
	
PRINT @SELECT

EXEC SP_EXECUTESQL @SELECT