USE MASTER
GO

DECLARE @TEXTO NVARCHAR(MAX);
DECLARE PONTEIRO CURSOR 
FOR 
	SELECT CONCAT('PRINT ''',NAME,'''; 
BEGIN
USE [', NAME, '] 
IF (OBJECT_ID(''LOGALTERACAOCLIENTE'') IS NOT NULL)
EXEC SP_EXECUTESQL N''
CREATE OR ALTER PROCEDURE [DBO].[TRANSF_MOV_CLIENTE]
@CLIOLD INTEGER,
@CLIOLDLOJA INTEGER,
@CLINEW INTEGER,
@CLINEWLOJA INTEGER
AS
DECLARE @BLOQUEADO INTEGER,
@NEGATIVADOUSE INTEGER ,
@NEGATIVADOSCPC INTEGER
BEGIN
  UPDATE BONUS SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE CHEQUEDEV SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE CHEQUEPRE SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE COBRANCAENVIADAS SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE CONTAREC SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE DEFEITO SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE DEMONSTRACAO SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE ECOMUNICACAO   SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE MOVIMENTOESTSAI SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE NEGATIVACAO SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE PEDIDOVENDA SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE FAMILIAR SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE FOTOFAMILIAR SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE VENDA SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA;
  UPDATE TROCA SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA
  UPDATE DOCUMENTODIGITALIZADO SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA
  UPDATE MOVIMENTOCAMPANHAFIDELIDADE SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA
  UPDATE CLIENTEENDERECOENTREGA SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA   WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA
  UPDATE OMNICHANNEL SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA
  UPDATE LOGALTERACAOCLIENTE SET CLIENTE = @CLINEW,CLIENTELOJA = @CLINEWLOJA WHERE CLIENTE = @CLIOLD AND CLIENTELOJA = @CLIOLDLOJA
  SELECT @BLOQUEADO =  BLOQUEADO, @NEGATIVADOUSE =  NEGATIVADOUSE, @NEGATIVADOSCPC =  NEGATIVADOSPC FROM CLIENTE  WHERE CODIGO = @CLIOLD AND LOJA = @CLIOLDLOJA
 
  IF @BLOQUEADO = 1
  BEGIN
  UPDATE CLIENTE
  SET BLOQUEADO = 1
  WHERE CODIGO = @CLINEW AND LOJA = @CLINEWLOJA
  END

  IF @NEGATIVADOSCPC = 1
  BEGIN
  UPDATE CLIENTE
  SET NEGATIVADOSPC = 1
  WHERE CODIGO = @CLINEW AND LOJA = @CLINEWLOJA
  END

  IF @NEGATIVADOUSE = 1
  BEGIN
  UPDATE CLIENTE
  SET NEGATIVADOUSE = 1
  WHERE CODIGO = @CLINEW AND LOJA = @CLINEWLOJA
  END   
END'';
END
') 
	FROM SYS.DATABASES D WHERE STATE = 0 AND DATABASE_ID > 4 AND 
		COALESCE((SELECT ROLE FROM SYS.DM_HADR_AVAILABILITY_REPLICA_STATES A WHERE A.REPLICA_ID = D.REPLICA_ID), 0) != 2
	ORDER BY NAME
OPEN PONTEIRO 
FETCH PONTEIRO INTO @TEXTO
WHILE (@@FETCH_STATUS = 0)
BEGIN
	EXECUTE SP_EXECUTESQL  @TEXTO; 
	FETCH NEXT FROM PONTEIRO INTO @TEXTO;		
END
CLOSE PONTEIRO;
DEALLOCATE PONTEIRO;	