--PROCESSOS
DECLARE @TEMP_SP_WHO2 TABLE
(
    SPID INT,
    STATUS VARCHAR(200) NULL,
    LOGIN SYSNAME NULL,
    HOSTNAME SYSNAME NULL,
    BLKBY SYSNAME NULL,
    DBNAME SYSNAME NULL,
    COMMAND VARCHAR(200) NULL,
    CPUTIME INT NULL,
    DISKIO INT NULL,
    LASTBATCH VARCHAR(200) NULL,
    PROGRAMNAME VARCHAR(500) NULL,
    SPID2 INT,
	REQUESTID INT NULL
)

--POPULA A TABELA DE PROCESSOS
INSERT  INTO @TEMP_SP_WHO2
EXEC SP_WHO2

SELECT CONCAT('KILL ', SPID) COMANDO_KILL, SPID, STATUS, HOSTNAME, DBNAME, PROGRAMNAME, BLKBY, COMMAND, COUNT(*) QTTHREADS,
	TRY_CAST('<QUERY> '+ CHAR (10)
	+(SELECT TEXT FROM SYS.SYSPROCESSES P OUTER APPLY SYS.DM_EXEC_SQL_TEXT(P.SQL_HANDLE) T WHERE P.SPID = TSW.SPID AND TEXT IS NOT NULL)
	+CHAR(10) + '</QUERY>' AS XML) AS _SQL
FROM    @TEMP_SP_WHO2 TSW
WHERE   1=1
	AND DBNAME = 'EDMAIS_HOMOLOGACAO_20201021'		--ESPECIFICA UM BANCO
	--AND COMMAND != 'AWAITING COMMAND'		--EXCLUI PROCESSOS EM STAND BY
	--AND (LTRIM(BLKBY) != '.' OR CAST(SPID AS VARCHAR(6)) IN (SELECT BLKBY FROM @TEMP_SP_WHO2))		--PEGA APENAS PROCESSOS BLOQUEADOS OU QUE ESTÃO BLOQUEANDO
GROUP BY SPID, STATUS, HOSTNAME, DBNAME, PROGRAMNAME, BLKBY, COMMAND
ORDER BY COMMAND